import { EmojiType } from "../constants";

export const ANIMAL_EMOJI: EmojiType[] = [
  { emoji: "🐶", description: "Dog", codePoint: 0x1f436 },
  { emoji: "🐱", description: "Cat", codePoint: 0x1f431 },
  { emoji: "🐭", description: "Mouse", codePoint: 0x1f42d },
  { emoji: "🐹", description: "Hamster", codePoint: 0x1f439 },
  { emoji: "🐰", description: "Rabbit", codePoint: 0x1f430 },
  { emoji: "🦊", description: "Fish", codePoint: 0x1f433 },
  { emoji: "🐻", description: "Bear", codePoint: 0x1f43b },
  { emoji: "🦁", description: "Lion", codePoint: 0x1f981 },
  { emoji: "🐯", description: "Tiger", codePoint: 0x1f42f },
  { emoji: "🦄", description: "Unicorn", codePoint: 0x1f984 },
  { emoji: "🐴", description: "Horse", codePoint: 0x1f434 },
  { emoji: "🐑", description: "Sheep", codePoint: 0x1f411 },
  { emoji: "🐑", description: "Sheep", codePoint: 0x1f411 },
  { emoji: "🐄", description: "Cow", codePoint: 0x1f404 },
  { emoji: "🐓", description: "Rooster", codePoint: 0x1f413 },
  { emoji: "🦉", description: "Owl", codePoint: 0x1f989 },
];

export const INSECT_EMOJI: EmojiType[] = [
  { emoji: "🐝", description: "Bee", codePoint: 0x1f41d },
  { emoji: "🐛", description: "Bug", codePoint: 0x1f41b },
  { emoji: "🐜", description: "Ant", codePoint: 0x1f41c },
  { emoji: "🦋", description: "Butterfly", codePoint: 0x1f98b },
  { emoji: "🕷️", description: "Spider", codePoint: 0x1f577 },
  { emoji: "🕸️", description: "Spider Web", codePoint: 0x1f578 },
  { emoji: "🪲", description: "Beetle", codePoint: 0x1f982 },
  { emoji: "🪳", description: "Cockroach", codePoint: 0x1f990 },
  { emoji: "🪰", description: "Fly", codePoint: 0x1f9fe },
  { emoji: "🪱", description: "Worm", codePoint: 0x1f41b },
];

export const COUNTRY_EMOJI: EmojiType[] = [
  {
    emoji: "🇦🇺",
    description: "Australia",
    codePoint: 0x1f1e6,
    codePoint2: 0x1f1fa,
  },
  {
    emoji: "🇧🇷",
    description: "Brazil",
    codePoint: 0x1f1e7,
    codePoint2: 0x1f1f7,
  },
  {
    emoji: "🇨🇦",
    description: "Canada",
    codePoint: 0x1f1e8,
    codePoint2: 0x1f1e6,
  },
  {
    emoji: "🇨🇳",
    description: "China",
    codePoint: 0x1f1e8,
    codePoint2: 0x1f1f3,
  },
  {
    emoji: "🇫🇷",
    description: "France",
    codePoint: 0x1f1e8,
    codePoint2: 0x1f1f7,
  },
  {
    emoji: "🇩🇪",
    description: "Germany",
    codePoint: 0x1f1e9,
    codePoint2: 0x1f1ea,
  },
  {
    emoji: "🇯🇵",
    description: "Japan",
    codePoint: 0x1f1ef,
    codePoint2: 0x1f1f5,
  },
  {
    emoji: "🇰🇷",
    description: "South Korea",
    codePoint: 0x1f1f0,
    codePoint2: 0x1f1f7,
  },
  {
    emoji: "🇲🇽",
    description: "Mexico",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1fd,
  },
  {
    emoji: "🇲🇪",
    description: "Montenegro",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1ea,
  },
  {
    emoji: "🇬🇧",
    description: "United Kingdom",
    codePoint: 0x1f1ec,
    codePoint2: 0x1f1e7,
  },
  {
    emoji: "🇺🇸",
    description: "United States",
    codePoint: 0x1f1fa,
    codePoint2: 0x1f1f8,
  },
  {
    emoji: "🇮🇳",
    description: "India",
    codePoint: 0x1f1ee,
    codePoint2: 0x1f1f3,
  },
  {
    emoji: "🇮🇹",
    description: "Italy",
    codePoint: 0x1f1ee,
    codePoint2: 0x1f1f9,
  },
  {
    emoji: "🇪🇸",
    description: "Spain",
    codePoint: 0x1f1ea,
    codePoint2: 0x1f1f8,
  },
  {
    emoji: "🇦🇹",
    description: "Austria",
    codePoint: 0x1f1e6,
    codePoint2: 0x1f1f9,
  },
  {
    emoji: "🇳🇱",
    description: "Netherlands",
    codePoint: 0x1f1f3,
    codePoint2: 0x1f1f1,
  },
  {
    emoji: "🇨🇴",
    description: "Colombia",
    codePoint: 0x1f1e8,
    codePoint2: 0x1f1f4,
  },
  {
    emoji: "🇧🇪",
    description: "Belgium",
    codePoint: 0x1f1e7,
    codePoint2: 0x1f1e9,
  },
  {
    emoji: "🇳🇿",
    description: "New Zealand",
    codePoint: 0x1f1f3,
    codePoint2: 0x1f1ff,
  },
  {
    emoji: "🇵🇹",
    description: "Portugal",
    codePoint: 0x1f1f5,
    codePoint2: 0x1f1f9,
  },
  {
    emoji: "🇵🇱",
    description: "Poland",
    codePoint: 0x1f1f5,
    codePoint2: 0x1f1f1,
  },
  {
    emoji: "🇪🇪",
    description: "Estonia",
    codePoint: 0x1f1ea,
    codePoint2: 0x1f1ea,
  },
  {
    emoji: "🇲🇬",
    description: "Madagascar",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1ec,
  },
  {
    emoji: "🇲🇳",
    description: "Mongolia",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1f3,
  },
  {
    emoji: "🇮🇩",
    description: "Indonesia",
    codePoint: 0x1f1ee,
    codePoint2: 0x1f1e9,
  },
  {
    emoji: "🇲🇲",
    description: "Myanmar",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1f2,
  },
  {
    emoji: "🇦🇪",
    description: "United Arab Emirates",
    codePoint: 0x1f1e6,
    codePoint2: 0x1f1ea,
  },
  {
    emoji: "🇮🇲",
    description: "Isle of Man",
    codePoint: 0x1f1ee,
    codePoint2: 0x1f1f2,
  },
  {
    emoji: "🇹🇭",
    description: "Thailand",
    codePoint: 0x1f1f9,
    codePoint2: 0x1f1ed,
  },
  {
    emoji: "🇻🇳",
    description: "Vietnam",
    codePoint: 0x1f1fb,
    codePoint2: 0x1f1f3,
  },
  {
    emoji: "🇧🇫",
    description: "Burkina Faso",
    codePoint: 0x1f1e7,
    codePoint2: 0x1f1eb,
  },
  {
    emoji: "🇧🇮",
    description: "Burundi",
    codePoint: 0x1f1e7,
    codePoint2: 0x1f1ee,
  },
  {
    emoji: "🇹🇲",
    description: "Turkmenistan",
    codePoint: 0x1f1f9,
    codePoint2: 0x1f1f2,
  },
  {
    emoji: "🇲🇦",
    description: "Morocco",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1e6,
  },
  {
    emoji: "🇰🇿",
    description: "Kazakhstan",
    codePoint: 0x1f1f0,
    codePoint2: 0x1f1ff,
  },
  {
    emoji: "🇯🇴",
    description: "Jordan",
    codePoint: 0x1f1ef,
    codePoint2: 0x1f1f4,
  },
  {
    emoji: "🇸🇩",
    description: "Sudan",
    codePoint: 0x1f1f8,
    codePoint2: 0x1f1e9,
  },
  {
    emoji: "🇸🇲",
    description: "San Marino",
    codePoint: 0x1f1f8,
    codePoint2: 0x1f1f2,
  },
  {
    emoji: "🇲🇿",
    description: "Mozambique",
    codePoint: 0x1f1f2,
    codePoint2: 0x1f1ff,
  },
  {
    emoji: "🇦🇿",
    description: "Azerbaijan",
    codePoint: 0x1f1e6,
    codePoint2: 0x1f1ff,
  },
  {
    emoji: "🇯🇪",
    description: "Jersey",
    codePoint: 0x1f1f0,
    codePoint2: 0x1f1e8,
  },
];

export const DESSERT_EMOJI: EmojiType[] = [
  { emoji: "🍰", description: "Shortcake", codePoint: 0x1f370 },
  { emoji: "🍮", description: "Custard", codePoint: 0x1f36e },
  { emoji: "🍪", description: "Cookie", codePoint: 0x1f36a },
  { emoji: "🍩", description: "Doughnut", codePoint: 0x1f369 },
  { emoji: "🍫", description: "Chocolate Bar", codePoint: 0x1f36b },
  { emoji: "🍬", description: "Candy", codePoint: 0x1f36c },
  { emoji: "🍭", description: "Lollipop", codePoint: 0x1f36d },
  { emoji: "🍨", description: "Ice Cream", codePoint: 0x1f368 },
  { emoji: "🍧", description: "Shaved Ice", codePoint: 0x1f367 },
  { emoji: "🍦", description: "Soft Ice Cream", codePoint: 0x1f366 },
  { emoji: "🥧", description: "Pie", codePoint: 0x1f967 },
  { emoji: "🍠", description: "Roasted Sweet Potato", codePoint: 0x1f360 },
  { emoji: "🧁", description: "Cupcake", codePoint: 0x1f9c1 },
];

export const DRINK_EMOJI: EmojiType[] = [
  { emoji: "🍵", description: "Teacup Without Handle", codePoint: 0x1f375 },
  { emoji: "🍶", description: "Sake", codePoint: 0x1f376 },
  { emoji: "🍾", description: "Bottle with Popping Cork", codePoint: 0x1f37e },
  { emoji: "🍷", description: "Wine Glass", codePoint: 0x1f377 },
  { emoji: "🍸", description: "Cocktail Glass", codePoint: 0x1f378 },
  { emoji: "🍹", description: "Tropical Drink", codePoint: 0x1f379 },
  { emoji: "🍺", description: "Beer Mug", codePoint: 0x1f37a },
  { emoji: "🍻", description: "Clinking Beer Mugs", codePoint: 0x1f37b },
  { emoji: "🥃", description: "Tumbler Glass", codePoint: 0x1f943 },
  { emoji: "🥤", description: "Cup with Straw", codePoint: 0x1f964 },
  { emoji: "🧃", description: "Juice Box", codePoint: 0x1f9c3 },
  { emoji: "🧉", description: "Mate Drink", codePoint: 0x1f9c9 },
  { emoji: "🧊", description: "Ice Cube", codePoint: 0x1f9ca },
  { emoji: "🧋", description: "Bubble Tea", codePoint: 0x1f9cb },
];

export const FOOD_EMOJI: EmojiType[] = [
  { emoji: "🍳", description: "Fried Egg", codePoint: 0x1f373 },
  { emoji: "🍲", description: "Stew", codePoint: 0x1f372 },
  { emoji: "🍜", description: "Steaming Bowl", codePoint: 0x1f35c },
  { emoji: "🍝", description: "Spaghetti", codePoint: 0x1f35d },
  { emoji: "🍛", description: "Curry Rice", codePoint: 0x1f35b },
  { emoji: "🍱", description: "Bento Box", codePoint: 0x1f371 },
  { emoji: "🍤", description: "Fried Shrimp", codePoint: 0x1f364 },
  { emoji: "🍣", description: "Sushi", codePoint: 0x1f363 },
  { emoji: "🍢", description: "Kebab", codePoint: 0x1f362 },
  { emoji: "🌭", description: "Hot Dog", codePoint: 0x1f32d },
  { emoji: "🍔", description: "Hamburger", codePoint: 0x1f354 },
  { emoji: "🍟", description: "French Fries", codePoint: 0x1f35f },
  { emoji: "🍕", description: "Pizza", codePoint: 0x1f355 },
  { emoji: "🍠", description: "Roasted Sweet Potato", codePoint: 0x1f360 },
  { emoji: "🥪", description: "Sandwich", codePoint: 0x1f96a },
  { emoji: "🥫", description: "Canned Food", codePoint: 0x1f96b },
  { emoji: "🥘", description: "Shallow Pan of Food", codePoint: 0x1f958 },
  { emoji: "🥣", description: "Bowl with Spoon", codePoint: 0x1f963 },
  { emoji: "🥡", description: "Takeout Box", codePoint: 0x1f961 },
  { emoji: "🥝", description: "Kiwi Fruit", codePoint: 0x1f95d },
  { emoji: "🍯", description: "Honey Pot", codePoint: 0x1f36f },
  { emoji: "🍰", description: "Shortcake", codePoint: 0x1f370 },
  { emoji: "🍪", description: "Cookie", codePoint: 0x1f36a },
  { emoji: "🍩", description: "Doughnut", codePoint: 0x1f369 },
  { emoji: "🍫", description: "Chocolate Bar", codePoint: 0x1f36b },
  { emoji: "🍬", description: "Candy", codePoint: 0x1f36c },
  { emoji: "🍭", description: "Lollipop", codePoint: 0x1f36d },
  { emoji: "🌮", description: "Taco", codePoint: 0x1f32e },
  { emoji: "🌯", description: "Burrito", codePoint: 0x1f32f },
  { emoji: "🥙", description: "Stuffed Flatbread", codePoint: 0x1f959 },
  { emoji: "🧆", description: "Falafel", codePoint: 0x1f9c6 },
  { emoji: "🥞", description: "Pancakes", codePoint: 0x1f95e },
  { emoji: "🧇", description: "Waffle", codePoint: 0x1f9c7 },
  { emoji: "🧈", description: "Butter", codePoint: 0x1f9c8 },
];
export const FRUIT_EMOJI: EmojiType[] = [
  { emoji: "🍏", description: "Green Apple", codePoint: 0x1f34f },
  { emoji: "🍎", description: "Red Apple", codePoint: 0x1f34e },
  { emoji: "🍐", description: "Pear", codePoint: 0x1f350 },
  { emoji: "🍑", description: "Peach", codePoint: 0x1f351 },
  { emoji: "🍒", description: "Cherries", codePoint: 0x1f352 },
  { emoji: "🍓", description: "Strawberry", codePoint: 0x1f353 },
  { emoji: "🍉", description: "Watermelon", codePoint: 0x1f349 },
  { emoji: "🍇", description: "Grapes", codePoint: 0x1f347 },
  { emoji: "🍈", description: "Melon", codePoint: 0x1f348 },
  { emoji: "🍋", description: "Lemon", codePoint: 0x1f34b },
  { emoji: "🍌", description: "Banana", codePoint: 0x1f34c },
  { emoji: "🍍", description: "Pineapple", codePoint: 0x1f34d },
  { emoji: "🥭", description: "Mango", codePoint: 0x1f96d },
  { emoji: "🥥", description: "Coconut", codePoint: 0x1f965 },
  { emoji: "🥝", description: "Kiwi Fruit", codePoint: 0x1f95d },
];

export const NATURE_EMOJI: EmojiType[] = [
  { emoji: "🌻", description: "Sunflower", codePoint: 0x1f33b },
  { emoji: "🌹", description: "Rose", codePoint: 0x1f339 },
  { emoji: "🌷", description: "Tulip", codePoint: 0x1f337 },
  { emoji: "🌼", description: "Blossom", codePoint: 0x1f33c },
  { emoji: "🌸", description: "Cherry Blossom", codePoint: 0x1f338 },
  { emoji: "🌺", description: "Hibiscus", codePoint: 0x1f33a },
  { emoji: "🍀", description: "Four Leaf Clover", codePoint: 0x1f340 },
  { emoji: "🍃", description: "Leaf Fluttering in Wind", codePoint: 0x1f343 },
  { emoji: "🍂", description: "Fallen Leaf", codePoint: 0x1f342 },
  { emoji: "🍁", description: "Maple Leaf", codePoint: 0x1f341 },
  { emoji: "🌿", description: "Herb", codePoint: 0x1f33f },
  { emoji: "🌵", description: "Cactus", codePoint: 0x1f335 },
  { emoji: "🌳", description: "Deciduous Tree", codePoint: 0x1f333 },
  { emoji: "🌲", description: "Evergreen Tree", codePoint: 0x1f332 },
  { emoji: "🌴", description: "Palm Tree", codePoint: 0x1f334 },
  { emoji: "🌵", description: "Cactus", codePoint: 0x1f335 },
  { emoji: "🌾", description: "Sheaf of Rice", codePoint: 0x1f33e },
  { emoji: "🌿", description: "Herb", codePoint: 0x1f33f },
  { emoji: "🍀", description: "Four Leaf Clover", codePoint: 0x1f340 },
];

export const SPORT_EMOJI: EmojiType[] = [
  { emoji: "⚽", description: "Soccer Ball", codePoint: 0x26bd },
  { emoji: "🏀", description: "Basketball", codePoint: 0x1f3c0 },
  { emoji: "🏈", description: "American Football", codePoint: 0x1f3c8 },
  { emoji: "⚾", description: "Baseball", codePoint: 0x26be },
  { emoji: "🎾", description: "Tennis", codePoint: 0x1f3be },
  { emoji: "🏐", description: "Volleyball", codePoint: 0x1f3d0 },
  { emoji: "🏉", description: "Rugby Football", codePoint: 0x1f3c9 },
  { emoji: "🎱", description: "Billiards", codePoint: 0x1f3b1 },
  { emoji: "🎳", description: "Bowling", codePoint: 0x1f3b3 },
  { emoji: "🏌️", description: "Golfer", codePoint: 0x1f3cc },
  { emoji: "🏄", description: "Surfer", codePoint: 0x1f3c4 },
  { emoji: "🚴", description: "Cyclist", codePoint: 0x1f6b4 },
  { emoji: "🚵", description: "Mountain Biker", codePoint: 0x1f6b5 },
  { emoji: "🏊", description: "Swimmer", codePoint: 0x1f3ca },
  { emoji: "🤽", description: "Water Polo", codePoint: 0x1f93d },
  { emoji: "🤾", description: "Handball", codePoint: 0x1f93e },
  { emoji: "🤸", description: "Cartwheel", codePoint: 0x1f938 },
  { emoji: "🤹", description: "Juggling", codePoint: 0x1f939 },
];

export const TRANSPORTATION_EMOJI: EmojiType[] = [
  { emoji: "🚗", description: "Automobile", codePoint: 0x1f697 },
  { emoji: "🚕", description: "Taxi", codePoint: 0x1f695 },
  { emoji: "🚙", description: "SUV", codePoint: 0x1f699 },
  { emoji: "🚚", description: "Delivery Truck", codePoint: 0x1f69a },
  { emoji: "🚛", description: "Articulated Lorry", codePoint: 0x1f69b },
  { emoji: "🚒", description: "Fire Engine", codePoint: 0x1f692 },
  { emoji: "🚓", description: "Police Car", codePoint: 0x1f693 },
  { emoji: "🚐", description: "Minibus", codePoint: 0x1f690 },
  { emoji: "🚆", description: "Train", codePoint: 0x1f686 },
  { emoji: "🚇", description: "Metro", codePoint: 0x1f687 },
  { emoji: "🚈", description: "Light Rail", codePoint: 0x1f688 },
  { emoji: "🚉", description: "Station", codePoint: 0x1f689 },
  { emoji: "🚊", description: "Tram", codePoint: 0x1f68a },
  { emoji: "🚝", description: "Monorail", codePoint: 0x1f69d },
  { emoji: "🚞", description: "Mountain Railway", codePoint: 0x1f69e },
  { emoji: "🚂", description: "Locomotive", codePoint: 0x1f682 },
  { emoji: "🚈", description: "Light Rail", codePoint: 0x1f688 },
  { emoji: "🚁", description: "Helicopter", codePoint: 0x1f681 },
  { emoji: "✈️", description: "Airplane", codePoint: 0x2708 },
  { emoji: "🚀", description: "Rocket", codePoint: 0x1f680 },
  { emoji: "🛸", description: "Flying Saucer", codePoint: 0x1f6f8 },
  { emoji: "🛳️", description: "Boat", codePoint: 0x1f6f3 },
  { emoji: "🚢", description: "Ship", codePoint: 0x1f6a2 },
  { emoji: "⛵", description: "Sailboat", codePoint: 0x26f5 },
  { emoji: "🚤", description: "Speedboat", codePoint: 0x1f6a4 },
  { emoji: "🛥️", description: "Motorboat", codePoint: 0x1f6a5 },
  { emoji: "🚡", description: "Aerial Tramway", codePoint: 0x1f6a1 },
  { emoji: "🚢", description: "Ship", codePoint: 0x1f6a2 },
];

export const VEGETABLE_EMOJI: EmojiType[] = [
  { emoji: "🥕", description: "Carrot", codePoint: 0x1f955 },
  { emoji: "🥒", description: "Cucumber", codePoint: 0x1f952 },
  { emoji: "🥬", description: "Leafy Green", codePoint: 0x1f96c },
  { emoji: "🥦", description: "Broccoli", codePoint: 0x1f966 },
  { emoji: "🌶️", description: "Hot Pepper", codePoint: 0x1f336 },
  { emoji: "🌽", description: "Corn", codePoint: 0x1f33d },
  { emoji: "🥔", description: "Potato", codePoint: 0x1f954 },
  { emoji: "🥕", description: "Carrot", codePoint: 0x1f955 },
];

export const WEATHER_EMOJI: EmojiType[] = [
  { emoji: "🌧️", description: "Cloud with Rain", codePoint: 0x1f327 },
  { emoji: "⛅", description: "Sun Behind Cloud", codePoint: 0x26c5 },
  { emoji: "🌨️", description: "Cloud with Snow", codePoint: 0x1f328 },
  {
    emoji: "⛈️",
    description: "Cloud with Lightning and Rain",
    codePoint: 0x1f329,
  },
  { emoji: "🌩️", description: "Cloud with Lightning", codePoint: 0x1f32a },
  { emoji: "🌫️", description: "Fog", codePoint: 0x1f32b },
  { emoji: "🌪️", description: "Tornado", codePoint: 0x1f32a },
  { emoji: "🌈", description: "Rainbow", codePoint: 0x1f308 },
  { emoji: "☀️", description: "Sun", codePoint: 0x2600 },
  { emoji: "☁️", description: "Cloud", codePoint: 0x2601 },
  { emoji: "⚡", description: "Lightning", codePoint: 0x26a1 },
  { emoji: "❄️", description: "Snowflake", codePoint: 0x2744 },
  { emoji: "💨", description: "Dashing Away", codePoint: 0x1f4a8 },
];
